name: iOS macOS Builder

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Archive iOS app (no device)
        run: |
          xcodebuild \
            -project Blank.xcodeproj \
            -scheme Blank \
            archive \
            -archivePath $PWD/build/Blank.xcarchive
